### ISSUE TITLE
Error during npm run create 

### ISSUE THREAD

**Issue by asunar** [arc-repos/arc-docs#19]
Going through the quickstart [here](https://arc.codes/quickstart/install). Setup the profile and the region in ~.aws/config like this
```

[profile personal]
region=us-west-1
```
package.json file:

```
...
    "precreate": "set AWS_DEFAULT_PROFILE=personal", 
    "create": "arc-create",
...
```

I get the following error.

```
C:\code\mytestapp>npm run create

> mytestapp@1.0.0 precreate C:\code\mytestapp
> set AWS_DEFAULT_PROFILE=personal


> mytestapp@1.0.0 create C:\code\mytestapp
> arc-create

C:\code\mytestapp\node_modules\@architect\parser\_get-sections.js:42
          throw SyntaxError(`invalid_section_value
          ^

SyntaxError: invalid_section_value
@section values cannot start with whitespace.

Invalid value: ""
```

What am I doing wrong?

**Comment by asunar** [comment]
Looks like _get_sections.js does not like the empty lines between sections.

**Comment by brianleroux** [comment]
Ah, yes your AWS creds are setup incorrectly. (I think.) The name needs to be a single value no spaces. Also your npm scripts should declare the env vars inline per quickstart instructions.

```
[default]
aws_access_key_id = 111
aws_secret_access_key = 111
region = us-east-1

[fake]
aws_access_key_id = 111
aws_secret_access_key = 111
region = us-east-1
```

**Comment by asunar** [comment]
AWS docs [here](http://docs.aws.amazon.com/cli/latest/userguide/cli-multiple-profiles.html) seem to suggest the [profile {profileName}] format so I was trying to follow that.

AWS docs also state

> The AWS CLI will also read credentials from the config file. If you want to keep all of your profile settings in a single file, you can.

I put all settings in the config file,removed the space and updated package.json to match the quickstart.
I'm still unable to run npm run create. Do I need to use a different syntax for env variable since I am on Windows?
![image](https://user-images.githubusercontent.com/204049/29139253-ddba5730-7d0b-11e7-9f2e-d0665a254a47.png)

**Comment by brianleroux** [comment]
ah! looks like the windows shell you are using needs `set`--- tho I'd recommend trying that new bash shell that windows 


can you try that and lmk if it works for you? (reopening b/c I think we can fix this with a crossenv module of some kind)

**Comment by asunar** [comment]
I'm on Windows 8 so I don't have the Linux Subsystem. 
The result of adding SET.
```
c:\code\mytestapp  (mytestapp@1.0.0)
λ npm run create

> mytestapp@1.0.0 create c:\code\mytestapp
> SET AWS_PROFILE=personal arc-create


c:\code\mytestapp  (mytestapp@1.0.0)
λ
```
Looks like arc-create is not executed so I added && .

```
c:\code\mytestapp  (mytestapp@1.0.0)
λ npm run create

> mytestapp@1.0.0 create c:\code\mytestapp
> SET AWS_PROFILE=personal && arc-create

c:\code\mytestapp\node_modules\aws-sdk\lib\request.js:31
            throw err;
            ^

CredentialsError: Missing credentials in config
    at ClientRequest.<anonymous> (c:\code\mytestapp\node_modules\aws-sdk\lib\http\node.js:83:34)
    at ClientRequest.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at ClientRequest.emit (events.js:185:7)
    at Socket.emitTimeout (_http_client.js:630:10)
    at Socket.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Socket.emit (events.js:185:7)
    at Socket._onTimeout (net.js:338:8)
    at ontimeout (timers.js:386:14)
```

I sprinkled a few console.logs, looks like Config.credentials object is null. For some reason the code was unable to create a creds object from the config (unchanged from the screenshot above).

**Comment by asunar** [comment]
FYI - Results of my env variables experiments

```
c:\code\mytestapp  (mytestapp@1.0.0)
λ SET AWS_PROFILE=default SET AWS_REGION=test

c:\code\mytestapp  (mytestapp@1.0.0)
λ echo %AWS_PROFILE%
default SET AWS_REGION=test

c:\code\mytestapp  (mytestapp@1.0.0)
λ SET AWS_PROFILE=default && SET AWS_REGION=test

c:\code\mytestapp  (mytestapp@1.0.0)
λ echo %AWS_PROFILE%
default

c:\code\mytestapp  (mytestapp@1.0.0)
λ echo %AWS_REGION%
test
```

**Comment by asunar** [comment]
Fails on Mac too 
![image](https://user-images.githubusercontent.com/204049/29147665-14c7710a-7d2e-11e7-8f35-1a34d6d5ca8e.png)

**Comment by brianleroux** [comment]
can you try with lowercase `set`?

`set AWS_PROFILE=default npm run create`

**Comment by brianleroux** [comment]
(also idk but this may help: https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/loading-node-credentials-shared.html)

**Comment by asunar** [comment]
Failed on a mac too :(

https://gifyu.com/image/zkNH

**Comment by asunar** [comment]
same result (Missing credentials in config) with lowercase set. Also tried running with admin account on windows and sudo on mac. I will checkout that link. Thanks.

**Comment by brianleroux** [comment]
I see the problem! 

Make sure the config is saved like so: 

- on a mac: `~/.aws/credentials` 
- on windows: `C:\Users\USER_NAME\.aws\credentials`

**Comment by asunar** [comment]
Kinda worked on the mac.

```
 alper@alpers-MacBook-Pro  ~/code/mytestapp  npm run create

> mytestapp@1.0.0 create /Users/alper/code/mytestapp
> AWS_PROFILE=personal AWS_REGION=us-west-1 arc-create

create @html code src/html/get-index
create @html testapp-production-get-index
create @html testapp-staging-get-index
create @json code src/json/get-api
create @json testapp-staging-get-api
create @json testapp-production-get-api
create @tables testapp-staging-arc-sessions
create @tables testapp-production-arc-sessions
{ TooManyRequestsException: Too Many Requests
    at Object.extractError (/Users/alper/code/mytestapp/node_modules/@architect/workflows/node_modules/aws-sdk/lib/protocol/json.js:48:27)
    at Request.extractError (/Users/alper/code/mytestapp/node_modules/@architect/workflows/node_modules/aws-sdk/lib/protocol/rest_json.js:37:8)
    at Request.callListeners (/Users/alper/code/mytestapp/node_modules/@architect/workflows/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/Users/alper/code/mytestapp/node_modules/@architect/workflows/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/alper/code/mytestapp/node_modules/@architect/workflows/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/alper/code/mytestapp/node_modules/@architect/workflows/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/alper/code/mytestapp/node_modules/@architect/workflows/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/alper/code/mytestapp/node_modules/@architect/workflows/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/alper/code/mytestapp/node_modules/@architect/workflows/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/alper/code/mytestapp/node_modules/@architect/workflows/node_modules/aws-sdk/lib/request.js:685:12)
  message: 'Too Many Requests',
  code: 'TooManyRequestsException',
  time: 2017-08-09T23:50:04.767Z,
  requestId: '778ab98c-7d5d-11e7-b71d-99e11d5b13bb',
  statusCode: 429,
  retryable: false,
  retryDelay: 18.21380998923834 }


/Users/alper/code/mytestapp/node_modules/@architect/workflows/node_modules/aws-sdk/lib/request.js:31
            throw err;
            ^

TypeError: Cannot read property 'id' of undefined
```

My .arc file does not have a tables section. Why is it trying to create tables? Thanks for your help/patience by the way.

**Comment by brianleroux** [comment]
oh hey thats good!!! 

those errors are aws throttling you which is sadly very normal. 🤷‍♂️ 

I wish I had a better solution but re-running `npm run create` is 👍 ---`arc` only creates things if they do not already exist and infra is supposed to be considered disposable so (I think) you now have everything working just fine! 👏 

by default `arc` creates a session table for any `@html` or `@json` routes defined --- if you don't want/need sessions you can just delete the tables and remove `SESSION_TABLE_NAME` environment variables from the lambdas (I need to document this!)

Thanks for _your patience this is super helpful for me to know what we need to improve. 💯

**Comment by asunar** [comment]
The only setup that worked on a Windows 8 - 64bit machine.
node (v6.11.2), npm (3.10.10)
Run shell as admin
No config file
No custom profile
No blank lines in .arc :man_shrugging: 
No setting env var in scripts section 😕 

I'm starting to see why most OSS maintainers don't want to deal with Windows. This is nuts.

![image](https://user-images.githubusercontent.com/204049/29157951-9dbc1390-7d6e-11e7-95e7-53a284abe061.png)

**Comment by brianleroux** [comment]
Ok, wow! The blank lines is def a [bug](https://github.com/arc-repos/arc-parser/issues/2)

And _I think_ we can fix the env vars thing with docs and/or https://www.npmjs.com/package/cross-env ---wdyt?

**Comment by asunar** [comment]
Sounds good to me. I also will test on another Windows machine to verify that it is not an issue with my special ❄️ machine.

**Comment by brianleroux** [comment]
ok! just updated the parser to accept the line breaks (I think) and updated `@architect/workflows@1.0.16` to use it!

**Comment by asunar** [comment]
confirmed, line breaks issue is fixed

**Comment by asunar** [comment]
I was able to make it work with named profiles using cross-env.

Used AWS_DEFAULT_PROFILE instead of AWS_PROFILE.

![image](https://user-images.githubusercontent.com/204049/29202778-f7c079e0-7e30-11e7-98c3-ac82f4df4947.png)

**Comment by asunar** [comment]
TIL

1. Setting the env variables is **required** regardless of the credentials and config files (why do I need to set the region env var? It is set in the config file)
2. Env variables do not reach out across && which creates an interesting issue.
    - Without &&, cannot execute multiple commands in Windows
    - With &&, previously set env variables are not available for subsequent commands

These issue makes cross-env a good candidate for enabling Windows users to call npm scripts.

**Comment by brianleroux** [comment]
@asunar thx so much for the help and pls let me know if you have anything to add to [these docs](https://github.com/arc-repos/arc-docs/commit/bcf706e14fbe23919de02ee03ebf08b32b88611e)!
