### ISSUE TITLE
update home page with info about JS Foundation governance

### ISSUE THREAD

**Issue by brianleroux** [arc-repos/arc-docs#24]

**Comment by brianleroux** [comment]
CC @kborchers ---any advice here? had someone mention one reason they wouldn't use Architect because they are concerned about the project longevity, which is awesome, and one of the things JS Foundation brings to the table. 

(For posterity: growing the committership is probably our first priority on the road to long term sustainability but having docs explain how/what/why the foundation model will help too!)

**Comment by kborchers** [comment]
The JS Foundations entire focus for projects is on long-term sustainability. You could start with references to the following items as ways we do that:
* https://js.foundation/about
* https://github.com/JSFoundation/TAC#the-js-foundation-technical-governance
* https://github.com/JSFoundation/TAC#mentors
* https://js.foundation/community/code-of-conduct
* Example of a project that has graduated from mentorship https://github.com/JSFoundation/TAC/blob/master/Projects/Appium.md
