### ISSUE TITLE
General doc issues

### ISSUE THREAD

**Issue by antstanley** [arc-repos/arc-docs#26]
Working through the install docs and a few missing pieces of information, so just listing them here...

* Quickstart/Setup - Required IAM permissions not mentioned. Might be useful to have a policy document that can be copied and pasted in AWS
* Quickstart/Setup - Doc mentions AWS_PROFILE & AWS_REGION environment variables need to be set, but in Quickstart/Install the recommended `scripts` json block sets them. Might need to clarify they don't need to be set globally up  front.
*Quickstart/Layout - Would be useful to put in a table all the elements of a .arc file with a 1 line description so you don't have to click on each one's link individually to find the difference ... Something like this..

Section | Purpose
------------ | -------------
@app | where you declare your app namespace
@domain | sets up DNS for a custom domain name. (ACM, API Gateway and Route53)
@html | section defines HTTP routes that return text/html content. (API Gateway and Lambda)
@json | section defines HTTP routes that return application/json content. (API Gateway and Lambda)
@events | define SNS topics and Lambda handlers for them. (SNS)
@scheduled | functions are invoked at the times you specify (Cloudwatch Events)
@slack | defines Slack app HTTP handlers. 
@tables | defines database tables and trigger functions for them (DynamoDB)
@indexes | defines additional database table indexes (DynamoDB)

I know some this is in the concepts page, but it was below the fold and I missed it first couple times!

~~One last thing... is there a way to delete everything that has been created by architect from within architect? I've just gone through the setup to understand how it works, now I want to remove the test functions....~~ wait ... found it! `npm run rm``

**Comment by brianleroux** [comment]
Awesome feedback: thank you! Will get this stuff updated today. A 🔑 choice for Architect that is def up for debate is that it **does not** remove infrastructure. Been intending to write a package that does cleanup based on a `.arc` but its low on my list of things to do and high on my list of things I might screw up. ;) 

Should maybe update the docs to reflect this?

**Comment by jonathanstiansen** [comment]
I really second the IAM policy thing, I'm trial and erring to find out the minimal subset - or even a superset that's not full admin over everything. 👍

**Comment by brianleroux** [comment]
FINALLY getting back to this ---anyone have an easy way / ideas to figure out what the IAM permissions would be? I guess I could create a locked down client and walk thru one by one?

**Comment by jonathanstiansen** [comment]
So far, a superset of the permissions is IAM, Lambda, Route53, CloudFront, API, Gateway, S3, SNS (simple notification service), CloudWatch Events, DynamoDB. 
I gave each Admin, but I'm sure that's more then needed. I believe that  the lambda full access one already includes some of the dynamo and S3 I think.

**Comment by brianleroux** [comment]
Hey y'all gonna reference this in the Wiki / Roadmap for now. I suspect the forthcoming CloudFormation work I'm about to merge changes this story…for the better!
